name: material3
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - /home/freeman/dev/projects/material3/
    - ios/
    - ios/Runner/
    - ios/Runner/Base.lproj/
    - ios/Runner/Assets.xcassets/
    - ios/Runner/Assets.xcassets/AppIcon.appiconset/
    - ios/Runner/Assets.xcassets/LaunchImage.imageset/
    - ios/Flutter/
    - ios/Runner.xcodeproj/
    - ios/Runner.xcodeproj/xcshareddata/
    - ios/Runner.xcodeproj/xcshareddata/xcschemes/
    - ios/Runner.xcodeproj/project.xcworkspace/
    - ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/
    - ios/Runner.xcworkspace/
    - ios/Runner.xcworkspace/xcshareddata/
    - web/
    - web/icons/
    - .git/
    - .git/info/
    - .git/logs/
    - .git/logs/refs/
    - .git/logs/refs/heads/
    - .git/logs/refs/remotes/
    - .git/logs/refs/remotes/origin/
    - .git/refs/
    - .git/refs/tags/
    - .git/refs/heads/
    - .git/refs/remotes/
    - .git/refs/remotes/origin/
    - .git/hooks/
    - .git/objects/
    - .git/objects/04/
    - .git/objects/05/
    - .git/objects/06/
    - .git/objects/09/
    - .git/objects/0a/
    - .git/objects/0b/
    - .git/objects/0d/
    - .git/objects/0e/
    - .git/objects/0f/
    - .git/objects/13/
    - .git/objects/14/
    - .git/objects/17/
    - .git/objects/18/
    - .git/objects/1d/
    - .git/objects/22/
    - .git/objects/23/
    - .git/objects/24/
    - .git/objects/27/
    - .git/objects/29/
    - .git/objects/2c/
    - .git/objects/2f/
    - .git/objects/30/
    - .git/objects/32/
    - .git/objects/33/
    - .git/objects/34/
    - .git/objects/36/
    - .git/objects/37/
    - .git/objects/38/
    - .git/objects/39/
    - .git/objects/3a/
    - .git/objects/3c/
    - .git/objects/3d/
    - .git/objects/3e/
    - .git/objects/42/
    - .git/objects/44/
    - .git/objects/45/
    - .git/objects/46/
    - .git/objects/47/
    - .git/objects/48/
    - .git/objects/49/
    - .git/objects/4a/
    - .git/objects/4c/
    - .git/objects/4d/
    - .git/objects/4f/
    - .git/objects/50/
    - .git/objects/53/
    - .git/objects/58/
    - .git/objects/59/
    - .git/objects/5a/
    - .git/objects/5b/
    - .git/objects/5d/
    - .git/objects/61/
    - .git/objects/63/
    - .git/objects/66/
    - .git/objects/69/
    - .git/objects/6c/
    - .git/objects/6d/
    - .git/objects/6e/
    - .git/objects/6f/
    - .git/objects/70/
    - .git/objects/72/
    - .git/objects/73/
    - .git/objects/74/
    - .git/objects/75/
    - .git/objects/76/
    - .git/objects/79/
    - .git/objects/7a/
    - .git/objects/7d/
    - .git/objects/80/
    - .git/objects/82/
    - .git/objects/84/
    - .git/objects/85/
    - .git/objects/88/
    - .git/objects/89/
    - .git/objects/8a/
    - .git/objects/8b/
    - .git/objects/91/
    - .git/objects/93/
    - .git/objects/94/
    - .git/objects/96/
    - .git/objects/9d/
    - .git/objects/a2/
    - .git/objects/a4/
    - .git/objects/a5/
    - .git/objects/a6/
    - .git/objects/a8/
    - .git/objects/aa/
    - .git/objects/b0/
    - .git/objects/b2/
    - .git/objects/b7/
    - .git/objects/b9/
    - .git/objects/ba/
    - .git/objects/bc/
    - .git/objects/bd/
    - .git/objects/bf/
    - .git/objects/c0/
    - .git/objects/c2/
    - .git/objects/c3/
    - .git/objects/c4/
    - .git/objects/c6/
    - .git/objects/c8/
    - .git/objects/cb/
    - .git/objects/cc/
    - .git/objects/cd/
    - .git/objects/ce/
    - .git/objects/d0/
    - .git/objects/d3/
    - .git/objects/d4/
    - .git/objects/d5/
    - .git/objects/d6/
    - .git/objects/d7/
    - .git/objects/da/
    - .git/objects/db/
    - .git/objects/dc/
    - .git/objects/dd/
    - .git/objects/df/
    - .git/objects/e0/
    - .git/objects/e1/
    - .git/objects/e3/
    - .git/objects/e6/
    - .git/objects/e7/
    - .git/objects/e9/
    - .git/objects/eb/
    - .git/objects/ed/
    - .git/objects/ee/
    - .git/objects/ef/
    - .git/objects/f0/
    - .git/objects/f1/
    - .git/objects/f2/
    - .git/objects/f3/
    - .git/objects/f5/
    - .git/objects/f6/
    - .git/objects/f7/
    - .git/objects/f9/
    - .git/objects/fa/
    - .git/objects/fe/
    - .git/objects/info/
    - .git/objects/pack/
    - .git/branches/
    - test/
    - .idea/
    - .idea/libraries/
    - .idea/runConfigurations/
    - .idea/inspectionProfiles/
    - linux/
    - linux/flutter/
    - linux/flutter/ephemeral/
    - linux/flutter/ephemeral/.plugin_symlinks/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/lib/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/test/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/test/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/include/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/linux/include/url_launcher_linux/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/example/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/example/lib/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/example/linux/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/example/linux/flutter/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/example/test_driver/
    - linux/flutter/ephemeral/.plugin_symlinks/url_launcher_linux/example/integration_test/
    - macos/
    - macos/Runner/
    - macos/Runner/Configs/
    - macos/Runner/Base.lproj/
    - macos/Runner/Assets.xcassets/
    - macos/Runner/Assets.xcassets/AppIcon.appiconset/
    - macos/Flutter/
    - macos/Flutter/ephemeral/
    - macos/Runner.xcodeproj/
    - macos/Runner.xcodeproj/xcshareddata/
    - macos/Runner.xcodeproj/xcshareddata/xcschemes/
    - macos/Runner.xcodeproj/project.xcworkspace/
    - macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/
    - macos/Runner.xcworkspace/
    - macos/Runner.xcworkspace/xcshareddata/
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/example/
    - android/app/src/main/kotlin/com/example/material3/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/
    - windows/
    - windows/runner/
    - windows/runner/resources/
    - windows/flutter/
    - windows/flutter/ephemeral/
    - windows/flutter/ephemeral/.plugin_symlinks/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/lib/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/lib/src/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/test/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/lib/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/windows/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/windows/runner/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/windows/runner/resources/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/windows/flutter/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/test_driver/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/example/integration_test/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/pigeons/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows/test/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows/include/
    - windows/flutter/ephemeral/.plugin_symlinks/url_launcher_windows/windows/include/url_launcher_windows/
    - .dart_tool/
    - .dart_tool/dartpad/
